// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pets.domain;

import com.pets.domain.MyOwner;

privileged aspect MyOwner_Roo_JavaBean {
    
    public String MyOwner.getFirstName() {
        return this.firstName;
    }
    
    public void MyOwner.setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
}
