// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pets.domain;

import com.pets.domain.Owner_;

privileged aspect Owner__Roo_JavaBean {
    
    public String Owner_.getFirstName() {
        return this.firstName;
    }
    
    public void Owner_.setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
}
