// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pets.domain;

import com.pets.domain.Owner_;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Owner__Roo_Configurable {
    
    declare @type: Owner_: @Configurable;
    
}
