// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.pets.domain;

import com.pets.domain.Visit;
import java.util.Date;

privileged aspect Visit_Roo_JavaBean {
    
    public Date Visit.getVisited() {
        return this.visited;
    }
    
    public void Visit.setVisited(Date visited) {
        this.visited = visited;
    }
    
}
